version: '3'

services:
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - 8888:15672
      - 5672:5672
    hostname: ticktok-rabbit

networks:
  default:
    external:
      name: ci-network

