version: 2

defaults: &defaults
  working_directory: ~/repo

jobs:
  test:
    <<: *defaults
    machine:
      image: circleci/classic:201808-01

    steps:
      - checkout

      - run:
          name: Run docker-compose.yml
          command: docker-compose up -d

      - run: sleep 20

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./.circleci/run_npm.sh ci
      - run: ./.circleci/run_npm.sh run ci-test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: docker-compose down

      - store_test_results:
          path: test-results

      - persist_to_workspace:
          root: ~/repo
          paths: .

  sanity:
    working_directory: ~/repo/sanity
    machine:
      image: circleci/classic:201808-01

    steps:
      - checkout

      - run:
          name: Run docker-compose.yml
          command: docker-compose up -d

      - run: sleep 20

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-sanity-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-sanity-dependencies-

      - run: ./.circleci/run_npm.sh ci
      - run: ./.circleci/run_npm.sh run ci-test

      - save_cache:
          paths:
            - node_modules
          key: v1-sanity-dependencies-{{ checksum "package.json" }}

      - run: docker-compose down

      - store_test_results:
          path: test-results

  deploy:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  ticktok-npm:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - sanity:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - sanity
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
